image: python:3.5-onbuild

services:
    - postgres:9.6

variables:
    POSTGRES_DB: manolo
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""

test:
    script:
      - pip install -r requirements/testing.txt
      - make coverage-gitlab
      - coverage report -m
      - coverage html
